# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0b1bc07d-a2b7-4ef4-90d4-599c156affed";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0b1bc07d-a2b7-4ef4-90d4-599c156affed".device = "/dev/disk/by-uuid/0b1bc07d-a2b7-4ef4-90d4-599c156affed";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/30EC-562E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-08b95d12-2e5d-499b-afc4-26333f868c7b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
